sonar.projectKey=drawhaus-backend
sonar.projectName=drawhaus-backend
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/__tests__/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
